@Library("checkoutgit") _

pipeline {
    agent any
    stages {
        stage('Code Checkout') {
            steps {
                script {
                  def workingDir = checkoutgit("https://github.com/Tanveer369/game.git", "main")
                  sh '''
                      ls -ltr
                  '''
                }
            }
        }
    }
}
